a:1:{s:5:"title";s:8:"Untitled";}
</div>

<div id="footerset">
  <p style="font-size:10px; text-align:center; clear:both;">- <a href="http:///admin/" style="text-decoration:underline; color:inherit;">Admin</a> -<br />Generated by <a href="http://comiccms.com/" target="_blank" style="text-decoration:underline; color:inherit;">ComicCMS</a><br />{{magic_executetime}} seconds</p>
</div>

</div>
</body>
</html>
